### PR TITLE
use default ports for neogo endpoints

### PR DESCRIPTION
**Pull request by 532910**
port is not required more

### CODE REVIEW

**Comment by carpawell** [comment]
Missing ports looks like smth that should return some HTML page to me. I feel it weird, do you have some common examples when a public service allows skipping port specifying?

**Comment by 532910** [comment]
let's do it vice versa: do you have some common examples when a public service port must be specified?

**Comment by AnnaShaleva** [comment]
Vote down from my side, status.fs is the last source of truth for me to check on various ports of our nodes.

**Comment by 532910** [comment]
> status.fs is the last source of truth for me to check on various ports of our nodes.

what exactly would you like to check and why do you need it?

**Comment by roman-khimov** [comment]
We don't have a clear agreement on the need of this change. But we have a tradition and well-known port numbers for P2P-HTTP-HTTPS services that are expected from the node. These ports are being used, that's what services listen to, so it's OK to have these ports exposed to the public. Therefore, NACK on this one.

**Pull request closed without merging**
